version: "3"

services:
  web:
    container_name: flashcards_web
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: unless-stopped
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:3333/api
    stdin_open: true
    